-- The key to using those tools [of Haskell] will be changing the way you think
-- from 'make data, then alter it' to 'define a function that would return the 
-- result, then apply to inputs'. 
--
-- You can convert an Integer to a Double with fromInteger
-- You can convert a Float to an Integer with truncate, round, ceiling, floor
